//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Model;
    
    public partial class HashtagManagerModel : DbContext
    {
        public HashtagManagerModel()
            : base("name=HashtagManagerModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Model.Entry> Entries { get; set; }
        public virtual DbSet<Model.Hashtag> Hashtags { get; set; }
        public virtual DbSet<Model.User> Users { get; set; }

        //Singleton Pattern
        private static HashtagManagerModel _instance;
        public static HashtagManagerModel Instance
        {
            get
            {
                if (_instance == null) _instance = new HashtagManagerModel();
                return _instance;
            }
        }
    }
}
